apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-tcp-udp
  namespace: test
spec:
  ports:
  - name: jvbtcp-port
    nodePort: 30000
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: jvbudp-port
    nodePort: 31000
    port: 31000
    protocol: UDP
    targetPort: 31000
  selector:
    service: jvb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

